// This file is automatically generated.
/* eslint-disable */
import * as TypeGraphQL from 'type-graphql';
export type FixDecorator<T> = T;

import { ObjectType } from 'type-graphql';

@ObjectType()
class User {
  @TypeGraphQL.Field(type => String)
  id!: string;

  @TypeGraphQL.Field(type => String)
  username!: string;
}

export { User };
